WITH BASE AS
(
    SELECT P.* FROM {{ref('master')}} P
)
SELECT P.RUNTIMESTAMP, P.DATEOFPORTFOLIO, P.ACCOUNTID, P.NUMBERID, P.ACCOUNTTYPE, P.ACCOUNTSOURCE, P.CUSTOMERID, P.ACCOUNTBALANCE, P.ACCOUNTPRINCIPAL,
P.AVAILABLEBALANCE, P.LIMIT, P.INTERESTACCRUED, P.INTERESTRATE, P.ANNUALRATE, P.TRANSFERRATE, P.TRANSFERSPREAD, P.PD, P.LGD, P.EXPECTEDCREDITLOSS,
P.STAGEOFECL, P.IMPAIREDFLAG, P.EXPOSUREATDEFAULT, P.RISKWEIGHT, P.TOTALRWA, P.CAPITALCHARGE, P.EXPOSUREGROUP, P.PORTFOLIOSEGMENT, P.CUSTOMERTIER,
P.RISKGRADE, P.RISKCLASS, P.RATEBUCKET, P.LIQUIDITYBUCKET, P.ARREARSBUCKET, P.FUNDINGSOURCE, P.STABLEFUNDINGFLAG, P.VINTAGE, P.GEOGRAPHICREGION, P.CURRENCY
FROM BASE P