WITH BASE AS
(
    SELECT P.* FROM {{ref('master')}} P
)

SELECT P.RUNTIMESTAMP, P.DATEOFPORTFOLIO, P.CUSTOMERID, COUNT(P.ACCOUNTID) AS TOTALACCOUNTS, SUM(P.ACCOUNTBALANCE) AS TOTALBALANCE,
SUM(P.ACCOUNTPRINCIPAL) AS TOTALPRINCIPAL, SUM(P.EXPOSUREATDEFAULT) AS TOTALEAD, SUM(P.EXPECTEDCREDITLOSS) AS TOTALECL, SUM(P.TOTALRWA) AS TOTALRWA,
SUM(P.CAPITALCHARGE) AS TOTALCAPITALCHARGE, SUM(P.INTERESTACCRUED) AS TOTALINTERESTACCRUED, AVG(P.PD) AS AVERAGEPD, AVG(P.LGD) AS AVERAGELGD,
AVG(P.INTERESTRATE) AS AVERAGEINTERESTRATE, MAX(P.RISKGRADE) AS HIGHESTRISKGRADE, MAX(P.STAGEOFECL) AS HIGHESTSTAGE, SUM(CASE WHEN P.IMPAIREDFLAG = 'Y'
THEN 1 ELSE 0 END) AS IMPAIREDACCOUNTS, P.CUSTOMERTIER, P.CUSTOMERRISKSEGMENT, P.GEOGRAPHICREGION
FROM BASE P
GROUP BY P.RUNTIMESTAMP, P.DATEOFPORTFOLIO, P.CUSTOMERID, P.CUSTOMERTIER, P.CUSTOMERRISKSEGMENT, P.GEOGRAPHICREGION