WITH BASE AS
(
    SELECT P.* FROM {{ref('master')}} P
)
SELECT P.RUNTIMESTAMP, P.DATEOFPORTFOLIO, P.ACCOUNTID, P.CUSTOMERID, P.ACCOUNTTYPE, P.EXPOSUREGROUP, P.EXPOSUREATDEFAULT, P.EXPOSURECLASS, P.EXPOSURESUBCLASS,
P.RISKWEIGHT, P.ONBALRWA, P.OFFBALRWA, P.TOTALRWA, P.CAPITALCHARGE, P.CAPITALBUFFERIMPACT, P.REGULATORYPD, P.REGULATORYLGD, P.BASELEXPECTEDLOSS,
P.REGULATORYASSETCLASS, P.ASSETCLASSADVANCED, P.LVRSOURCE, P.STRESSADJUSTEDPD, P.STRESSADJUSTEDLGD, P.STRESSLOSSESTIMATE, P.STRESSSCENARIOFLAG, P.RISKGRADE,
P.RISKCLASS, P.GEOGRAPHICREGION, P.VINTAGE
FROM BASE P