WITH SOURCE AS
(
    SELECT S.*
    FROM {{ source('RAW', 'RETAIL_LOANS') }} S
),
SIMULATED_PARAMS AS
(
    SELECT SP.*
    FROM {{ source('RAW', 'SIMULATED_PARAMETERS') }} SP
),
PASS1 AS
(
    SELECT S.*, SP.ARREARSFLAG, SP.ARREARSPCT, SP.PROVISIONFLAG, SP.PROVISIONPCT, SP.CASHBACKFLAG, SP.CASHBACKPCT, SP.ADVANCEPCT, SP.COLLATERALPCT, SP.FUNDINGCOSTPCT,
    SP.FEESAMOUNTPCT, SP.OPERATIONALCOSTPCT
    FROM SOURCE S
    LEFT JOIN SIMULATED_PARAMS SP ON S.ACCOUNTID = SP.ACCOUNTID AND S.RUNTIMESTAMP = SP.RUNTIMESTAMP
),
PASS2 AS
(
    SELECT P.*, FC.FEESCHARGED, FC.FUNDINGCOST, FC.OPERATIONALCOST, FTP.INTERESTRATETYPE, FTP.BASERATE, FTP.ADDONRATE, FTP.BASISCOST, FTP.LIQUIDITYRATE, FTP.FUNDINGINDEX, SI.STRESSSCORE,
    SI.MACROVOLATILITYINDEX, SI.WITHDRAWALHISTORY
    FROM PASS1 P
    LEFT JOIN {{ source('RAW', 'FEES_COSTS') }} FC ON P.ACCOUNTID = FC.ACCOUNTID AND P.RUNTIMESTAMP = FC.RUNTIMESTAMP
    LEFT JOIN {{ source('RAW', 'FTP_INPUTS') }} FTP ON P.ACCOUNTID = FTP.ACCOUNTID AND P.RUNTIMESTAMP = FTP.RUNTIMESTAMP
    LEFT JOIN {{ source('RAW', 'STRESS_INPUTS') }} SI ON P.ACCOUNTID = SI.ACCOUNTID AND P.RUNTIMESTAMP = SI.RUNTIMESTAMP
),
PASS3 AS
(
    SELECT P.*, SUM(P.ACCOUNTBALANCE) OVER (PARTITION BY P.CUSTOMERID) AS TOTALCUSTOMEREXPOSURE, AVG(P.BASERATE) OVER (PARTITION BY P.CUSTOMERID) AS AVERAGEBASERATE,
    AVG(P.ADDONRATE) OVER (PARTITION BY P.CUSTOMERID) AS AVERAGEADDONRATE, AVG(P.BASISCOST) OVER (PARTITION BY P.CUSTOMERID) AS AVERAGEBASISCOST,
    AVG(P.INTERESTRATE) OVER (PARTITION BY P.CUSTOMERID) AS AVERAGEINTERESTRATE, P.MARKETVALUE AS LIMIT, CASE WHEN P.ACCOUNTSOURCE = 'RTE' THEN 'RETL'
    WHEN P.ACCOUNTSOURCE = 'BBK' AND P.ACCOUNTBALANCE > 1000000 THEN 'CORP' WHEN P.COLLATERALCATEGORY = 'Residential Property' THEN 'RESI'
    WHEN P.COLLATERALCATEGORY IN ('Commercial', 'Agri', 'Dev Finance') THEN 'COMM' ELSE 'N/A' END AS EXPOSUREGROUP, CASE WHEN P.ACCOUNTBALANCE /
    NULLIF(P.MARKETVALUE, 0) > 0.80 THEN 'Y' ELSE 'N' END AS LMIFLAG, P.ACCOUNTBALANCE / NULLIF(P.MARKETVALUE, 0) AS LVR
    FROM PASS2 P
),
DATE_CALCS AS
(
    SELECT P.*, DATEDIFF('DAY', P.DATEOFORIGINATION, P.DATEOFPORTFOLIO) AS DAYSSINCEORIGINATION,
    DATEDIFF('DAY', P.DATEOFSETTLEMENT, P.DATEOFPORTFOLIO) AS DAYSSINCESETTLEMENT, DATEDIFF('DAY', P.DATEOFPORTFOLIO, P.DATEOFMATURITY) AS DAYSUNTILMATURITY,
    DATEDIFF('YEAR', P.DATEOFORIGINATION, P.DATEOFPORTFOLIO) AS RELATIONSHIPLENGTHYEARS, DAY(DATEOFPORTFOLIO) AS DAYOFMONTH,
    YEAR(P.DATEOFPORTFOLIO) * 100 + MONTH(P.DATEOFPORTFOLIO) AS VINTAGE, ROUND(DATEDIFF('DAY', P.DATEOFPORTFOLIO, P.DATEOFMATURITY) / 30, 0) AS TERM
    FROM PASS3 P
),
RATE_CALCS AS
(
    SELECT P.*, P.INTERESTRATE / 100 AS ANNUALRATE, (P.INTERESTRATE / 100) / 365 AS DAILYRATE, (P.INTERESTRATE / 100) / 12 AS MONTHLYRATE,
    CASE WHEN P.AMORTIZATIONTYPE = 'P&I' THEN P.ACCOUNTBALANCE * ((P.INTERESTRATE / 100) / 12) * POWER(1 + ((P.INTERESTRATE/ 100) / 12), P.TERM)
    / (POWER(1 + ((P.INTERESTRATE / 100) / 12), P.TERM) - 1) WHEN P.AMORTIZATIONTYPE = 'InterestOnly' THEN P.ACCOUNTBALANCE * ((P.INTERESTRATE / 100) / 12)
    WHEN P.AMORTIZATIONTYPE = 'Bullet' THEN 0.0 ELSE 0.0 END AS MONTHLYREPAYMENT
    FROM DATE_CALCS P
),
BALANCE_CALCS AS
(
    SELECT P.*, ABS(P.ACCOUNTBALANCE) AS ACCOUNTPRINCIPAL, P.LIMIT - P.ACCOUNTBALANCE AS AVAILABLEBALANCE, P.ACCOUNTBALANCE * P.ADVANCEPCT AS ADVANCEAMOUNT,
    P.ACCOUNTBALANCE * P.CASHBACKPCT AS CASHBACKAMOUNT, ABS(P.ACCOUNTBALANCE) * P.COLLATERALPCT AS ALLOCATEDCASHCOLLATERAL, P.ACCOUNTBALANCE *
    (P.INTERESTRATE / 100.0) * (DAYSSINCESETTLEMENT / 365) AS INTERESTACCRUED, P.ACCOUNTBALANCE * P.DAYOFMONTH AS AGGREGATEDMONTHLYBALANCE,
    (P.ACCOUNTBALANCE * P.DAYOFMONTH) / P.DAYOFMONTH AS AVERAGEMONTHLYBALANCE
    FROM RATE_CALCS P
),
EXPOSURE_CALCS AS
(
    SELECT P.*, P.ACCOUNTBALANCE - P.ALLOCATEDCASHCOLLATERAL AS INTERESTNOTBOUGHTTOACCOUNT, CASE WHEN P.ACCOUNTBALANCE <= 0 THEN 0.0
    WHEN P.INTERESTACCRUED + P.ACCOUNTBALANCE - (P.ACCOUNTBALANCE - P.ALLOCATEDCASHCOLLATERAL) - P.ALLOCATEDCASHCOLLATERAL <= 0 THEN 0.0
    ELSE P.INTERESTACCRUED + P.ACCOUNTBALANCE - (P.ACCOUNTBALANCE - P.ALLOCATEDCASHCOLLATERAL) - P.ALLOCATEDCASHCOLLATERAL END AS EXPOSUREATDEFAULT,
    GREATEST(P.INTERESTACCRUED + P.ACCOUNTBALANCE, 0) AS EXPOSURENETCREDIT, CASE WHEN P.ACCOUNTBALANCE <= 0 THEN 0.0
    WHEN P.INTERESTACCRUED + P.ACCOUNTBALANCE - (P.ACCOUNTBALANCE - P.ALLOCATEDCASHCOLLATERAL) - P.ALLOCATEDCASHCOLLATERAL <= 0 THEN 0.0
    ELSE P.INTERESTACCRUED + P.ACCOUNTBALANCE - (P.ACCOUNTBALANCE - P.ALLOCATEDCASHCOLLATERAL) - P.ALLOCATEDCASHCOLLATERAL END AS ONBALANCEEXPOSUREAMT,
    P.AVAILABLEBALANCE AS OFFBALAMOUNT, 1.0 AS CREDITCONVERSIONFACTOR, P.AVAILABLEBALANCE + P.CASHBACKAMOUNT AS CREDITEXPOSUREAMOUNT,
    P.AVAILABLEBALANCE + P.ACCOUNTPRINCIPAL + P.ADVANCEAMOUNT AS TOTALACCOUNTEXPOSURE, P.AVAILABLEBALANCE + P.CASHBACKAMOUNT AS CAPITALOFFBALANCEAMOUNT
    FROM BALANCE_CALCS P
),
ECL_CALCS AS
(
    SELECT P.*, 1 - LEAST(GREATEST(P.CREDITSCORE / 1000.0, 0.01), 0.99) AS PD, LEAST(GREATEST(0.25 + LEAST(GREATEST(0.15 * (P.LVR - 0.60),
    -0.10), 0.30) + (-0.05 * CASE WHEN P.LMIFLAG = 'Y' THEN 1 ELSE 0 END) + (0.20 * LEAST(P.ARREARSAMOUNT / NULLIF(P.MARKETVALUE, 0), 1.0)),
    0.10), 0.90) AS LGD, (1 - LEAST(GREATEST(P.CREDITSCORE / 1000.0, 0.01), 0.99)) * LEAST(GREATEST(0.25 + LEAST(GREATEST(0.15 * (P.LVR - 0.60),
    -0.10), 0.30) + (-0.05 * CASE WHEN P.LMIFLAG = 'Y' THEN 1 ELSE 0 END) + (0.20 * LEAST(P.ARREARSAMOUNT / NULLIF(P.MARKETVALUE, 0), 1.0)),
    0.10), 0.90) * P.EXPOSUREATDEFAULT AS EXPECTEDCREDITLOSS, CASE WHEN P.ARREARSDAYS >= 60 THEN 3 WHEN P.ARREARSDAYS >= 30 THEN 2
    WHEN P.ARREARSDAYS >= 1 THEN 1 ELSE 0 END AS STAGEOFECL, SUM(P.TOTALACCOUNTEXPOSURE) OVER (PARTITION BY P.CUSTOMERID) AS TOTALGROUPEXPOSURE,
    CASE WHEN P.ACCOUNTSOURCE = 'BBK' THEN SUM(P.TOTALACCOUNTEXPOSURE) OVER (PARTITION BY P.CUSTOMERID) ELSE 0.0 END AS TOTALBUSINESSGROUPEXPOSURE
    FROM EXPOSURE_CALCS P
),
ECL_STAGE_CALCS AS
(
    SELECT P.*, CASE WHEN P.STAGEOFECL = 1 THEN P.EXPECTEDCREDITLOSS ELSE 0.0 END AS STAGE1ECL, CASE WHEN P.STAGEOFECL = 2 THEN
    P.EXPECTEDCREDITLOSS ELSE 0.0 END AS STAGE2ECL, CASE WHEN P.STAGEOFECL = 3 THEN P.EXPECTEDCREDITLOSS ELSE 0.0 END AS STAGE3ECL,
    CASE WHEN P.STAGEOFECL = 1 THEN P.PD ELSE 0.0 END AS STAGE1PD, CASE WHEN P.STAGEOFECL = 2 THEN P.PD ELSE 0.0 END AS STAGE2PD,
    CASE WHEN P.STAGEOFECL = 3 THEN P.PD ELSE 0.0 END AS STAGE3PD, CASE WHEN P.STAGEOFECL = 1 THEN P.LGD ELSE 0.0 END AS STAGE1LGD,
    CASE WHEN P.STAGEOFECL = 2 THEN P.LGD ELSE 0.0 END AS STAGE2LGD, CASE WHEN P.STAGEOFECL = 3 THEN P.LGD ELSE 0.0 END AS STAGE3LGD,
    CASE WHEN P.STAGEOFECL = 3 THEN P.EXPECTEDCREDITLOSS ELSE 0.0 END AS IMPAIREDNET, CASE WHEN P.STAGEOFECL = 3 THEN 'Y' ELSE 'N' END AS IMPAIREDFLAG
    FROM ECL_CALCS P
),
FTP_CALCS AS
(
    SELECT P.*, P.BASERATE + P.ADDONRATE AS TRANSFERRATE, (P.BASERATE + P.ADDONRATE) - P.INTERESTRATE AS TRANSFERSPREAD, P.BASERATE -
    P.INTERESTRATE AS BASISCALCULATION, P.INTERESTRATE AS IRRCALCULATION, P.INTERESTRATE - P.FUNDINGINDEX AS EXPECTEDRETURN, 0 AS LIQUIDITYPREMIUM,
    P.FUNDINGINDEX + P.BASISCOST + P.LIQUIDITYRATE AS FUNDINGCOSTRATE
    FROM ECL_STAGE_CALCS P
),
STRESS_CALCS AS
(
    SELECT P.*, LEAST(GREATEST(P.PD * 1.5 + 0.05 * P.STRESSSCORE + 0.05 * P.MACROVOLATILITYINDEX, 0.001), 0.999) AS STRESSADJUSTEDPD,
    LEAST(GREATEST(P.LGD + 0.10 + CASE WHEN P.LVR > 0.80 THEN 0.05 ELSE 0.0 END, 0.10), 0.90) AS STRESSADJUSTEDLGD,
    CASE WHEN P.STRESSSCORE + P.MACROVOLATILITYINDEX > 1.2 THEN 'Severe' ELSE 'Base' END AS STRESSSCENARIOFLAG, LEAST(GREATEST(P.PD * 1.5 +
    0.05 * P.STRESSSCORE + 0.05 * P.MACROVOLATILITYINDEX, 0.001), 0.999) * LEAST(GREATEST(P.LGD + 0.10, 0.10), 0.90) * P.EXPOSUREATDEFAULT
    AS STRESSLOSSESTIMATE, P.WITHDRAWALHISTORY * P.MACROVOLATILITYINDEX AS WITHDRAWALRISK
    FROM FTP_CALCS P
),
REGULATORY_CALCS AS
(
    SELECT P.*, LEAST(GREATEST(P.PD, 0.003), 0.20) AS REGULATORYPD, CASE WHEN P.COLLATERALCATEGORY = 'Residential Property' AND
    P.LVR <= 0.8 AND P.AMORTIZATIONTYPE = 'P&I' THEN 0.20 WHEN P.COLLATERALCATEGORY = 'Residential Property' THEN 0.35
    WHEN P.COLLATERALCATEGORY IN ('Commercial', 'Agri', 'Dev Finance') AND P.LVR <= 0.6 AND P.AMORTIZATIONTYPE = 'P&I' THEN 0.45
    WHEN P.COLLATERALCATEGORY IN ('Commercial', 'Agri', 'Dev Finance') THEN 0.60 ELSE 0.60 END AS REGULATORYLGD, LEAST(GREATEST(P.PD, 0.003), 0.20)
    * CASE WHEN P.COLLATERALCATEGORY = 'Residential Property' AND P.LVR <= 0.8 AND P.AMORTIZATIONTYPE = 'P&I' THEN 0.20
    WHEN P.COLLATERALCATEGORY = 'Residential Property' THEN 0.35 WHEN P.COLLATERALCATEGORY IN ('Commercial', 'Agri', 'Dev Finance') AND
    P.LVR <= 0.6 AND P.AMORTIZATIONTYPE = 'P&I' THEN 0.45 WHEN P.COLLATERALCATEGORY IN ('Commercial', 'Agri', 'Dev Finance') THEN 0.60
    ELSE 0.60 END * P.EXPOSUREATDEFAULT AS BASELEXPECTEDLOSS, CASE WHEN P.COLLATERALCATEGORY = 'Residential Property' AND P.LVR <= 0.8 AND
    P.AMORTIZATIONTYPE = 'P&I' THEN 'Standard Residential Mortgage' WHEN P.COLLATERALCATEGORY = 'Residential Property' THEN
    'Non-standard Residential Mortgage' WHEN P.COLLATERALCATEGORY IN ('Commercial', 'Agri', 'Dev Finance') AND P.LVR <= 0.6 AND
    P.AMORTIZATIONTYPE = 'P&I' THEN 'Standard Commercial Property' WHEN P.COLLATERALCATEGORY IN ('Commercial', 'Agri', 'Dev Finance') THEN
    'Non-standard Commercial Property' WHEN P.COLLATERALCATEGORY IN ('PI', 'Other') THEN 'Other Secured Exposure' ELSE 'Unsecured Exposure'
    END AS REGULATORYASSETCLASS, CASE WHEN P.TOTALCUSTOMEREXPOSURE > 5000000 THEN 'General Corporate - Other' WHEN
    P.TOTALCUSTOMEREXPOSURE > 1500000 THEN 'General Corporate - SME Corporate' ELSE 'General Corporate - SME Retail' END AS ASSETCLASSADVANCED,
    CASE WHEN P.ACCOUNTTYPE = 'Retail Loan' THEN '0 - Resi LVR' WHEN P.ACCOUNTSOURCE = 'FWD' THEN '1 - LVR Orig'
    WHEN P.ACCOUNTTYPE = 'Business Loan' THEN '2 - BB CR' ELSE 'Missing' END AS LVRSOURCE, CASE WHEN CEIL((1000 - P.CREDITSCORE) / 35) < 1
    THEN 1 WHEN CEIL((1000 - P.CREDITSCORE) / 35) > 20 THEN 20 ELSE CAST(CEIL((1000 - P.CREDITSCORE) / 35) AS INT) END AS RISKGRADE,
    CASE WHEN CEIL((1000 - P.CREDITSCORE) / 35) <= 6 THEN 'Low' WHEN CEIL((1000 - P.CREDITSCORE) / 35) <= 12 THEN 'Medium' ELSE 'High' END AS RISKCLASS,
    CASE WHEN P.EXPOSUREGROUP = 'RETL' AND P.LMIFLAG = 'Y' THEN 0.50 WHEN P.EXPOSUREGROUP = 'RETL' AND P.LMIFLAG = 'N' THEN 0.75
    WHEN P.EXPOSUREGROUP = 'CORP' THEN 1.00 ELSE 0.50 END AS RISKWEIGHT, P.EXPOSUREATDEFAULT * CASE WHEN P.EXPOSUREGROUP = 'RETL' AND
    P.LMIFLAG = 'Y' THEN 0.50 WHEN P.EXPOSUREGROUP = 'RETL' AND P.LMIFLAG = 'N' THEN 0.75 WHEN P.EXPOSUREGROUP = 'CORP' THEN 1.00
    ELSE 0.50 END AS ONBALRWA, GREATEST(P.EXPOSURENETCREDIT - P.TRANSFERRATE, 0) * CASE WHEN P.EXPOSUREGROUP = 'RETL' AND P.LMIFLAG = 'Y'
    THEN 0.50 WHEN P.EXPOSUREGROUP = 'RETL' AND P.LMIFLAG = 'N' THEN 0.75 WHEN P.EXPOSUREGROUP = 'CORP' THEN 1.00 ELSE 0.50 END AS OFFBALRWA,
    (P.EXPOSUREATDEFAULT + GREATEST(P.EXPOSURENETCREDIT - P.TRANSFERRATE, 0)) * CASE WHEN P.EXPOSUREGROUP = 'RETL' AND P.LMIFLAG = 'Y'
    THEN 0.50 WHEN P.EXPOSUREGROUP = 'RETL' AND P.LMIFLAG = 'N' THEN 0.75 WHEN P.EXPOSUREGROUP = 'CORP' THEN 1.00 ELSE 0.50 END AS TOTALRWA,
    (P.EXPOSUREATDEFAULT + GREATEST(P.EXPOSURENETCREDIT - P.TRANSFERRATE, 0)) * CASE WHEN P.EXPOSUREGROUP = 'RETL' AND P.LMIFLAG = 'Y'
    THEN 0.50 WHEN P.EXPOSUREGROUP = 'RETL' AND P.LMIFLAG = 'N' THEN 0.75 WHEN P.EXPOSUREGROUP = 'CORP' THEN 1.00 ELSE 0.50 END * 0.08 AS CAPITALCHARGE,
    (P.EXPOSUREATDEFAULT + GREATEST(P.EXPOSURENETCREDIT - P.TRANSFERRATE, 0)) * CASE WHEN P.EXPOSUREGROUP = 'RETL' AND P.LMIFLAG = 'Y'
    THEN 0.50 WHEN P.EXPOSUREGROUP = 'RETL' AND P.LMIFLAG = 'N' THEN 0.75 WHEN P.EXPOSUREGROUP = 'CORP' THEN 1.00 ELSE 0.50 END *
    (0.025 + CASE WHEN P.EXPOSUREGROUP = 'CORP' THEN 0.01 ELSE 0.0 END) AS CAPITALBUFFERIMPACT, CASE WHEN P.COLLATERALCATEGORY =
    'Residential Property' AND P.LVR <= 0.8 AND P.AMORTIZATIONTYPE = 'P&I' THEN 'Standard Residential Mortgage' WHEN P.COLLATERALCATEGORY =
    'Residential Property' THEN 'Non-standard Residential Mortgage' WHEN P.COLLATERALCATEGORY IN ('Commercial', 'Agri', 'Dev Finance') AND
    P.LVR <= 0.6 AND P.AMORTIZATIONTYPE = 'P&I' THEN 'Standard Commercial Property' WHEN P.COLLATERALCATEGORY IN ('Commercial', 'Agri',
    'Dev Finance') THEN 'Non-standard Commercial Property' WHEN P.COLLATERALCATEGORY IN ('PI', 'Other') THEN 'Other Secured Exposure'
    ELSE 'Unsecured Exposure' END AS EXPOSURECLASS, P.LVR * 100 AS LVRRWA, CASE WHEN (P.LVR * 100) <= 5 THEN '0 to <= 5%' WHEN (P.LVR * 100)
     <= 10 THEN '5 to <= 10%' WHEN (P.LVR * 100) <= 15 THEN '10 to <= 15%' WHEN (P.LVR * 100) <= 20 THEN '15 to <= 20%'
     WHEN (P.LVR * 100) <= 25 THEN '20 to <= 25%' WHEN (P.LVR * 100) <= 30 THEN '25 to <= 30%'
     WHEN (P.LVR * 100) <= 35 THEN '30 to <= 35%' WHEN (P.LVR * 100) <= 40 THEN '35 to <= 40%'
     WHEN (P.LVR * 100) <= 45 THEN '40 to <= 45%' WHEN (P.LVR * 100) <= 50 THEN '45 to <= 50%'
     WHEN (P.LVR * 100) <= 55 THEN '50 to <= 55%' WHEN (P.LVR * 100) <= 60 THEN '55 to <= 60%'
     WHEN (P.LVR * 100) <= 65 THEN '60 to <= 65%' WHEN (P.LVR * 100) <= 70 THEN '65 to <= 70%'
     WHEN (P.LVR * 100) <= 75 THEN '70 to <= 75%' WHEN (P.LVR * 100) <= 80 THEN '75 to <= 80%'
     WHEN (P.LVR * 100) <= 85 THEN '80 to <= 85%' WHEN (P.LVR * 100) <= 90 THEN '85 to <= 90%'
     WHEN (P.LVR * 100) <= 95 THEN '90 to <= 95%' WHEN (P.LVR * 100) <= 100 THEN '95 to <= 100%' ELSE '>100%' END AS LVRBAND
    FROM STRESS_CALCS P
),
CUSTOMER_CALCS AS
(
    SELECT P.*, CASE WHEN P.TOTALCUSTOMEREXPOSURE > 5000000 THEN 'Platinum' WHEN P.TOTALCUSTOMEREXPOSURE > 1500000 THEN 'Gold'
    WHEN P.TOTALCUSTOMEREXPOSURE > 500000 THEN 'Silver' ELSE 'Bronze' END AS CUSTOMERTIER, CASE WHEN P.PD > 0.25 THEN 'High'
    WHEN P.PD > 0.10 THEN 'Medium' ELSE 'Low' END AS CUSTOMERRISKSEGMENT, CASE WHEN P.EXPOSUREGROUP = 'RETL' THEN 'Retail Mortgage'
    WHEN P.EXPOSUREGROUP = 'COMM' THEN 'Commercial Property' WHEN P.EXPOSUREGROUP = 'RESI' THEN 'Residential Mortgage'
    WHEN P.EXPOSUREGROUP = 'CORP' THEN 'Corporate' ELSE 'Other' END AS PORTFOLIOSEGMENT, CASE WHEN P.COLLATERALCATEGORY = 'Agri'
    THEN 'AGRI' WHEN P.COLLATERALCATEGORY = 'Commercial' THEN 'COMM' WHEN P.COLLATERALCATEGORY = 'Dev Finance' THEN 'DEVF'
    WHEN P.COLLATERALCATEGORY = 'PI' THEN 'PI' WHEN P.COLLATERALCATEGORY = 'Other' THEN 'OTHER' WHEN P.COLLATERALCATEGORY =
    'Residential Property' THEN 'RESI' ELSE 'UNSEC' END AS INDUSTRYSECTOR, 'N' AS CROSSSELLFLAG,
    (P.INTERESTACCRUED + P.FEESCHARGED - P.EXPECTEDCREDITLOSS - P.FUNDINGCOST - P.OPERATIONALCOST) / NULLIF(P.CAPITALCHARGE, 0) AS RAROC,
    CASE WHEN P.TOTALBUSINESSGROUPEXPOSURE > 5000000 THEN 'General Corporate - Other'
    WHEN P.TOTALBUSINESSGROUPEXPOSURE > 1500000 THEN 'General Corporate - SME Corporate'
    ELSE 'General Corporate - SME Retail' END AS EXPOSURESUBCLASS, P.ACCOUNTBALANCE / NULLIF(P.LIMIT, 0) AS SOURCELVR,
    P.ACCOUNTPRINCIPAL * P.RISKWEIGHT AS RISKWEIGHTEDASSETLVR
    FROM REGULATORY_CALCS P
),
CLASSIFICATIONS AS
(
    SELECT P.*, CASE WHEN P.INTERESTRATE <= 2 THEN '<=2%' WHEN P.INTERESTRATE <= 4 THEN '2-4%' WHEN P.INTERESTRATE <= 6 THEN '4-6%'
    WHEN P.INTERESTRATE <= 8 THEN '6-8%' ELSE '>8%' END AS RATEBUCKET, CASE WHEN P.EXPOSUREATDEFAULT / NULLIF(P.LIMIT, 0) <= 0.25
    THEN '<=25%' WHEN P.EXPOSUREATDEFAULT / NULLIF(P.LIMIT, 0) <= 0.50 THEN '25-50%' WHEN P.EXPOSUREATDEFAULT / NULLIF(P.LIMIT, 0) <= 0.75
    THEN '50-75%' WHEN P.EXPOSUREATDEFAULT / NULLIF(P.LIMIT, 0) <= 1.00 THEN '75-100%' ELSE '>100%' END AS UTILISATIONBUCKET,
    RANK() OVER (PARTITION BY P.CUSTOMERID ORDER BY P.TOTALACCOUNTEXPOSURE DESC) AS GROUPEXPOSURERANK, CASE WHEN P.TERM <= 12 THEN 'Short'
    WHEN P.TERM <= 36 THEN 'Medium' ELSE 'Long' END AS LIQUIDITYBUCKET, CASE WHEN P.ACCOUNTSOURCE = 'BBK' AND P.ACCOUNTPRINCIPAL > 1000000
    THEN 'Wholesale' ELSE 'Retail' END AS FUNDINGSOURCE, CASE WHEN P.TERM >= 12 THEN 'Y' ELSE 'N' END AS STABLEFUNDINGFLAG,
    CASE WHEN P.CURRENCY != 'AUD' THEN P.EXPOSUREATDEFAULT * 0.10 ELSE 0.0 END AS FXSHOCKIMPACT, P.EXPOSUREATDEFAULT * CASE WHEN
    P.EXPOSUREGROUP = 'CORP' THEN 0.01 ELSE 0.005 END AS CREDITSPREADSHOCKIMPACT, P.ACCOUNTPRINCIPAL * 0.02 * (P.TERM / 12.0) AS
    INTERESTRATESHOCKIMPACT, CASE WHEN P.ARREARSDAYS > 0 THEN 1 ELSE 0 END AS DPDLAG, CASE WHEN P.ARREARSDAYS > 0 THEN 'Y' ELSE 'N' END AS DPDFLAG,
    CASE WHEN P.LIMIT > 0 THEN P.EXPOSUREATDEFAULT / P.LIMIT ELSE 0.0 END AS EADUTILISATION,
    CASE WHEN P.EXPOSUREATDEFAULT > 0 THEN P.EXPOSUREATDEFAULT / NULLIF(P.ACCOUNTPRINCIPAL, 0) ELSE NULL END AS EXPOSUREDENSITY,
    CASE WHEN P.IMPAIREDFLAG = 'Y' AND P.COLLATERALCATEGORY = 'Residential Property' THEN 'Defaulted Resi Property'
    WHEN P.IMPAIREDFLAG = 'Y' AND P.ACCOUNTPROVISION != 0 AND (P.ACCOUNTBALANCE - P.INTERESTNOTBOUGHTTOACCOUNT) < 0 THEN 'Other Defaulted Property > 0.2'
    WHEN P.IMPAIREDFLAG = 'Y' THEN 'Other Defaulted Property < 0.2' ELSE NULL END AS DEFAULTEDEXPOSURECLASS,
    CASE WHEN P.ARREARSDAYS = 0 THEN '0' WHEN P.ARREARSDAYS <= 29 THEN '1-29' WHEN P.ARREARSDAYS <= 59 THEN '30-59'
    WHEN P.ARREARSDAYS <= 89 THEN '60-89' ELSE '90+' END AS ARREARSBUCKET, P.DAYSSINCESETTLEMENT / 30.0 AS SEASONINGMONTHS,
    P.TERM / 12.0 AS TENORYEARS, CASE WHEN P.AMORTIZATIONTYPE = 'InterestOnly' THEN 'Y' ELSE 'N' END AS IOFLAG, CASE WHEN
    P.AMORTIZATIONTYPE = 'Bullet' THEN 'Y' ELSE 'N' END AS BULLETFLAG, AVG(P.INTERESTRATE) OVER (PARTITION BY P.CUSTOMERID) AS AVERAGEINTERESTRATEWINDOW
    FROM CUSTOMER_CALCS P
)

SELECT * FROM CLASSIFICATIONS
