WITH SOURCE AS
(
    SELECT S.*
    FROM {{ source('RAW', 'RETAIL_DEPOSITS') }} S
),
SIMULATED_PARAMS AS
(
    SELECT SP.*
    FROM {{ source('RAW', 'SIMULATED_PARAMETERS') }} SP
),
PASS1 AS
(
    SELECT S.*, SP.ARREARSFLAG, SP.ARREARSPCT, SP.PROVISIONFLAG, SP.PROVISIONPCT, SP.CASHBACKFLAG, SP.CASHBACKPCT, SP.ADVANCEPCT, SP.COLLATERALPCT, SP.FUNDINGCOSTPCT,
    SP.FEESAMOUNTPCT, SP.OPERATIONALCOSTPCT, SP.MONTHLYDEPOSITFREQUENCY
    FROM SOURCE S
    LEFT JOIN SIMULATED_PARAMS SP ON S.ACCOUNTID = SP.ACCOUNTID AND S.RUNTIMESTAMP = SP.RUNTIMESTAMP
),
PASS2 AS
(
    SELECT P.*, FC.FEESCHARGED, FC.FUNDINGCOST, FC.OPERATIONALCOST, FTP.INTERESTRATETYPE, FTP.BASERATE, FTP.ADDONRATE, FTP.BASISCOST, FTP.LIQUIDITYRATE, FTP.FUNDINGINDEX, SI.STRESSSCORE,
    SI.MACROVOLATILITYINDEX, SI.WITHDRAWALHISTORY
    FROM PASS1 P
    LEFT JOIN {{ source('RAW', 'FEES_COSTS') }} FC ON P.ACCOUNTID = FC.ACCOUNTID AND P.RUNTIMESTAMP = FC.RUNTIMESTAMP
    LEFT JOIN {{ source('RAW', 'FTP_INPUTS') }} FTP ON P.ACCOUNTID = FTP.ACCOUNTID AND P.RUNTIMESTAMP = FTP.RUNTIMESTAMP
    LEFT JOIN {{ source('RAW', 'STRESS_INPUTS') }} SI ON P.ACCOUNTID = SI.ACCOUNTID AND P.RUNTIMESTAMP = SI.RUNTIMESTAMP
),
PASS3 AS
(
    SELECT P.*, SUM(P.ACCOUNTBALANCE) OVER (PARTITION BY P.CUSTOMERID) AS TOTALCUSTOMEREXPOSURE, AVG(P.BASERATE) OVER (PARTITION BY P.CUSTOMERID) AS AVERAGEBASERATE,
    AVG(P.ADDONRATE) OVER (PARTITION BY P.CUSTOMERID) AS AVERAGEADDONRATE, AVG(P.BASISCOST) OVER (PARTITION BY P.CUSTOMERID) AS AVERAGEBASISCOST,
    AVG(P.INTERESTRATE) OVER (PARTITION BY P.CUSTOMERID) AS AVERAGEINTERESTRATE
    FROM PASS2 P
),
DATE_CALCS AS
(
    SELECT P.*, DATEDIFF('DAY', P.DATEOFORIGINATION, P.DATEOFPORTFOLIO) AS DAYSSINCEORIGINATION, 0 AS TERM, NULL AS LIMIT,
    DATEDIFF('YEAR', P.DATEOFORIGINATION, P.DATEOFPORTFOLIO) AS RELATIONSHIPLENGTHYEARS, 'Retail Deposit' AS TYPEOFACCOUNT,
    YEAR(P.DATEOFPORTFOLIO) * 100 + MONTH(P.DATEOFPORTFOLIO) AS VINTAGE, DAY(DATEOFPORTFOLIO) AS DAYOFMONTH, NULL AS AVAILABLEBALANCE
    FROM PASS3 P
),
RATE_CALCS AS
(
    SELECT P.*, P.INTERESTRATE / 100 AS ANNUALRATE, (P.INTERESTRATE / 100) / 365 AS DAILYRATE, (P.INTERESTRATE / 100) / 12 AS MONTHLYRATE
    FROM DATE_CALCS P
),
BALANCE_CALCS AS
(
    SELECT P.*, ABS(P.ACCOUNTBALANCE) AS ACCOUNTPRINCIPAL, P.ACCOUNTBALANCE * P.ADVANCEPCT AS ADVANCEAMOUNT,
    P.ACCOUNTBALANCE * P.CASHBACKPCT AS CASHBACKAMOUNT, P.ACCOUNTBALANCE * P.COLLATERALPCT AS ALLOCATEDCASHCOLLATERAL,
    P.ACCOUNTBALANCE * P.DAYOFMONTH AS AGGREGATEDMONTHLYBALANCE, (P.ACCOUNTBALANCE * P.DAYOFMONTH) / P.DAYOFMONTH AS AVERAGEMONTHLYBALANCE,
    P.ACCOUNTBALANCE * (P.INTERESTRATE / 100) * (P.DAYSSINCEORIGINATION / 365) AS INTERESTACCRUED
    FROM RATE_CALCS P
),
EXPOSURE_CALCS AS
(
    SELECT P.*, P.INTERESTACCRUED - P.ALLOCATEDCASHCOLLATERAL AS INTERESTNOTBOUGHTTOACCOUNT,
    CASE WHEN P.ACCOUNTBALANCE <= 0 THEN 0 WHEN P.INTERESTACCRUED + P.ACCOUNTBALANCE - (P.ACCOUNTPRINCIPAL * P.ALLOCATEDCASHCOLLATERAL)
    - P.ALLOCATEDCASHCOLLATERAL <= 0 THEN 0 ELSE P.INTERESTACCRUED + P.ACCOUNTBALANCE - (P.ACCOUNTPRINCIPAL * P.ALLOCATEDCASHCOLLATERAL)
    - P.ALLOCATEDCASHCOLLATERAL END AS EXPOSUREATDEFAULT, 0.0 AS EXPOSURENETCREDIT,
    CASE WHEN P.INTERESTACCRUED + P.ACCOUNTBALANCE - (P.ACCOUNTPRINCIPAL * P.ALLOCATEDCASHCOLLATERAL) - P.ALLOCATEDCASHCOLLATERAL < 0
    THEN 0 ELSE P.INTERESTACCRUED + P.ACCOUNTBALANCE - (P.ACCOUNTPRINCIPAL * P.ALLOCATEDCASHCOLLATERAL) - P.ALLOCATEDCASHCOLLATERAL END
    AS ONBALANCEEXPOSUREAMT, 0.0 AS CREDITEXPOSUREAMOUNT, 0.0 AS OFFBALAMOUNT, 0.0 AS CREDITCONVERSIONFACTOR, ABS(P.ACCOUNTBALANCE) -
    P.ADVANCEAMOUNT AS CREDITEXPOSUREAMOUNTCASHBACK, P.ACCOUNTPRINCIPAL AS TOTALACCOUNTEXPOSURE
    FROM BALANCE_CALCS P
),
ECL_CALCS AS
(
    SELECT P.*, 1 - LEAST(GREATEST(P.CREDITSCORE / 1000.0, 0.01), 0.99) AS PD, LEAST(GREATEST(0.25 + LEAST(GREATEST(0.15 * (0.0 - 0.60),
    -0.10), 0.30) + (-0.05 * 0) + (0.20 * 0.0), 0.10), 0.90) AS LGD, (1 - LEAST(GREATEST(P.CREDITSCORE / 1000.0, 0.01), 0.99))
    * LEAST(GREATEST(0.25, 0.10), 0.90) * P.EXPOSUREATDEFAULT AS EXPECTEDCREDITLOSS, 0 AS STAGEOFECL
    FROM EXPOSURE_CALCS P
),
ECL_STAGE_CALCS AS
(
    SELECT P.*, CASE WHEN P.STAGEOFECL = 1 THEN P.EXPECTEDCREDITLOSS ELSE 0.0 END AS STAGE1ECL,
    CASE WHEN P.STAGEOFECL = 2 THEN P.EXPECTEDCREDITLOSS ELSE 0.0 END AS STAGE2ECL, CASE WHEN P.STAGEOFECL = 3 THEN P.EXPECTEDCREDITLOSS ELSE 0.0 END AS STAGE3ECL,
    CASE WHEN P.STAGEOFECL = 1 THEN P.PD ELSE 0.0 END AS STAGE1PD, CASE WHEN P.STAGEOFECL = 2 THEN P.PD ELSE 0.0 END AS STAGE2PD,
    CASE WHEN P.STAGEOFECL = 3 THEN P.PD ELSE 0.0 END AS STAGE3PD, CASE WHEN P.STAGEOFECL = 1 THEN P.LGD ELSE 0.0 END AS STAGE1LGD,
    CASE WHEN P.STAGEOFECL = 2 THEN P.LGD ELSE 0.0 END AS STAGE2LGD, CASE WHEN P.STAGEOFECL = 3 THEN P.LGD ELSE 0.0 END AS STAGE3LGD,
    CASE WHEN P.STAGEOFECL = 3 THEN P.EXPECTEDCREDITLOSS ELSE 0.0 END AS IMPAIREDNET, CASE WHEN P.STAGEOFECL = 3 THEN 'Y' ELSE 'N' END AS IMPAIREDFLAG
    FROM ECL_CALCS P
),
FTP_CALCS AS
(
    SELECT P.*, P.BASERATE + P.ADDONRATE AS TRANSFERRATE, (P.BASERATE + P.ADDONRATE) - P.INTERESTRATE AS TRANSFERSPREAD,
    P.BASERATE - P.INTERESTRATE AS BASISCALCULATION, P.INTERESTRATE AS IRRCALCULATION, P.INTERESTRATE - P.FUNDINGINDEX AS EXPECTEDRETURN,
    0 AS LIQUIDITYPREMIUM
    FROM ECL_STAGE_CALCS P
),
STRESS_CALCS AS
(
    SELECT P.*, LEAST(GREATEST(P.PD * 1.5 + 0.05 * P.STRESSSCORE + 0.05 * P.MACROVOLATILITYINDEX, 0.001), 0.999) AS STRESSADJUSTEDPD,
    LEAST(GREATEST(P.LGD + 0.10, 0.10), 0.90) AS STRESSADJUSTEDLGD, CASE WHEN P.STRESSSCORE + P.MACROVOLATILITYINDEX > 1.2 THEN 'Severe'
    ELSE 'Base' END AS STRESSSCENARIOFLAG, LEAST(GREATEST(P.PD * 1.5 + 0.05 * P.STRESSSCORE + 0.05 * P.MACROVOLATILITYINDEX, 0.001), 0.999)
    * LEAST(GREATEST(P.LGD + 0.10, 0.10), 0.90) * P.EXPOSUREATDEFAULT AS STRESSLOSSESTIMATE, P.WITHDRAWALHISTORY * P.MACROVOLATILITYINDEX AS WITHDRAWALRISK
    FROM FTP_CALCS P
),
REGULATORY_CALCS AS
(
    SELECT P.*, LEAST(GREATEST(P.PD, 0.003), 0.20) AS REGULATORYPD, P.LGD AS REGULATORYLGD, LEAST(GREATEST(P.PD, 0.003), 0.20) * P.LGD * P.EXPOSUREATDEFAULT AS BASELEXPECTEDLOSS,
    NULL AS REGULATORYASSETCLASS, NULL AS ASSETCLASSADVANCED, 'N/A' AS LVRSOURCE, CASE WHEN CEIL((1000 - P.CREDITSCORE) / 35) < 1 THEN 1
    WHEN CEIL((1000 - P.CREDITSCORE) / 35) > 20 THEN 20 ELSE CAST(CEIL((1000 - P.CREDITSCORE) / 35) AS INT) END AS RISKGRADE,
    CASE WHEN CEIL((1000 - P.CREDITSCORE) / 35) <= 6 THEN 'Low' WHEN CEIL((1000 - P.CREDITSCORE) / 35) <= 12 THEN 'Medium' ELSE 'High'
    END AS RISKCLASS
    FROM STRESS_CALCS P
),
CUSTOMER_CALCS AS
(
    SELECT P.*, CASE WHEN P.TOTALCUSTOMEREXPOSURE > 5000000 THEN 'Platinum' WHEN P.TOTALCUSTOMEREXPOSURE > 1500000 THEN 'Gold'
    WHEN P.TOTALCUSTOMEREXPOSURE > 500000 THEN 'Silver' ELSE 'Bronze' END AS CUSTOMERTIER, CASE WHEN P.PD > 0.25 THEN 'High'
    WHEN P.PD > 0.10 THEN 'Medium' ELSE 'Low' END AS CUSTOMERRISKSEGMENT, 'Retail Deposit' AS PORTFOLIOSEGMENT, NULL AS INDUSTRYSECTOR,
    'N' AS CROSSSELLFLAG, NULL AS RAROC
    FROM REGULATORY_CALCS P
),
CLASSIFICATIONS AS
(
    SELECT P.*, CASE WHEN P.INTERESTRATE <= 2 THEN '<=2%' WHEN P.INTERESTRATE <= 4 THEN '2-4%' WHEN P.INTERESTRATE <= 6 THEN '4-6%'
    WHEN P.INTERESTRATE <= 8 THEN '6-8%' ELSE '>8%' END AS RATEBUCKET, CASE WHEN P.EXPOSUREATDEFAULT / NULLIF(P.ACCOUNTBALANCE, 0) <= 0.25
    THEN '<=25%' WHEN P.EXPOSUREATDEFAULT / NULLIF(P.ACCOUNTBALANCE, 0) <= 0.50 THEN '25-50%' WHEN P.EXPOSUREATDEFAULT /
    NULLIF(P.ACCOUNTBALANCE, 0) <= 0.75 THEN '50-75%' WHEN P.EXPOSUREATDEFAULT / NULLIF(P.ACCOUNTBALANCE, 0) <= 1.00 THEN '75-100%'
    ELSE '>100%' END AS UTILISATIONBUCKET, CASE WHEN P.TOTALCUSTOMEREXPOSURE > 0  THEN
    RANK() OVER (PARTITION BY P.CUSTOMERID ORDER BY P.TOTALACCOUNTEXPOSURE DESC) ELSE NULL END AS GROUPEXPOSURERANK,
    CASE WHEN P.TERM <= 12 THEN 'Short' WHEN P.TERM <= 36 THEN 'Medium' ELSE 'Long' END AS LIQUIDITYBUCKET, 'Retail' AS FUNDINGSOURCE,
    'Y' AS STABLEFUNDINGFLAG, CASE WHEN P.CURRENCY != 'AUD' THEN P.EXPOSUREATDEFAULT * 0.10 ELSE 0.0 END AS FXSHOCKIMPACT,
    P.EXPOSUREATDEFAULT * 0.005 AS CREDITSPREADSHOCKIMPACT, P.ACCOUNTPRINCIPAL * 0.02 * (P.TERM / 12.0) AS INTERESTRATESHOCKIMPACT,
    0 AS DPDLAG, 'N' AS DPDFLAG, 0.0 AS EADUTILISATION, CASE WHEN P.EXPOSUREATDEFAULT > 0 THEN P.EXPOSUREATDEFAULT /
    NULLIF(P.ACCOUNTPRINCIPAL, 0) ELSE NULL END AS EXPOSUREDENSITY, NULL AS DEFAULTEDEXPOSURECLASS, '0' AS ARREARSBUCKET
    FROM CUSTOMER_CALCS P
)

SELECT * FROM CLASSIFICATIONS
